apiVersion: apps/v1
kind: Deployment
metadata:
  name: rahiapp-deployment

spec:
  replicas: 2   # initial pods (HPA baad me control karega)

  selector:
    matchLabels:
      app: rahiapp

  template:
    metadata:
      labels:
        app: rahiapp

    spec:
      containers:
        - name: rahiapp
          image: rahiregistry.azurecr.io/rahi-app-image:latest

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev   # 👈 change env (dev,prod,stag,uat)

          # 🔥 IMPORTANT for HPA
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20