apiVersion: apps/v1
kind: Deployment
metadata:
  name: rahiapp-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: rahiapp

  template:
    metadata:
      labels:
        app: rahiapp

    spec:
      containers:
        - name: rahiapp
          image: rahiregistry.azurecr.io/rahi-app-image:latest  # placeholder only

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stg

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20