name: Build and Deploy to AKS

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Java setup
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      # 3. Build app
      - name: Build with Gradle
        run: ./gradlew build

      # 4. Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5. ACR Login
      - name: Login to ACR
        run: |
          az acr login --name rahiregistry

      # 6. Build & Push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t rahiregistry.azurecr.io/rahi-app-image:${{ github.sha }} .
          docker push rahiregistry.azurecr.io/rahi-app-image:${{ github.sha }}

      # 7. Replace image tag
      - name: Update deployment image
        run: |
          sed -i "s/IMAGE_TAG_PLACEHOLDER/${{ github.sha }}/g" k8s/deployment.yaml

      # 8. Set AKS context
      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: RahiCluster
          resource-group: rahi-resource

      # 9. Deploy FIRST
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # 10. Set env AFTER deploy
      - name: Set Spring Profile
        run: |
          kubectl set env deployment/rahiapp-deployment SPRING_PROFILES_ACTIVE=dev --overwrite